### ISSUE TITLE
Size of the representation of Fans since to be computed incorrectly the first time speed is changed

### ISSUE THREAD

**Issue by adaussy** [ObeoNetwork/Flow-Designer#20]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=576423.

![bug-taille](https://user-images.githubusercontent.com/4439675/135826023-7d35b58f-9948-4aae-b99b-189368343295.gif)

**Comment by lredor** [comment]
This issue is fixed with OD CE 11.7.0. It includesSirius 7.0.1. OD CE 11.7.0 is coming soon.
